version: "3.3"

services:
  db:
    build:
      context: ./postgres
    volumes:
      - ./postgres/volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    command: ["postgres", "-c", "log_statement=all"]
